import { z } from 'zod';

export const CaseStatusSchema = z.enum([
    'pending', 'crawling', 'analyzed', 'assigned', 'reviewing',
    'first_review_completed', 'lawyer_confirmed', 'emailed',
    'client_replied', 'client_viewed', 'contract_sent', 'contract_signed',
    'cold_email', 'guide_download', 'pilot_offer', 'subscribed',
    'upsell', 'churn_risk', 're_investigation', 'rejected', 'invalid_site'
]).catch('pending');

export const IssueSchema = z.object({
    id: z.string().catch(() => `err-${Date.now()}`),
    level: z.enum(['HIGH', 'MEDIUM', 'LOW']).catch('LOW'),
    law: z.string().catch(''),
    title: z.string().catch('알 수 없는 이슈'),
    originalText: z.string().catch(''),
    riskDesc: z.string().catch(''),
    scenario: z.string().optional().catch(undefined),
    penalty: z.string().optional().catch(undefined),
    recommendation: z.string().optional().catch(undefined),
    customDraft: z.string().catch(''),
    lawyerNote: z.string().catch(''),
    reviewChecked: z.boolean().catch(false),
    aiDraftGenerated: z.boolean().catch(false),
});

export const LawyerProfileSchema = z.object({
    id: z.string().catch('unknown-lawyer-id'),
    name: z.string().catch('미지정 변호사'),
    role: z.string().catch('lawyer'),
    signatureImageUrl: z.string().optional().catch(undefined),
    createdAt: z.string().optional().catch(undefined),
});

export const CompanyContactSchema = z.object({
    id: z.string().catch(() => `contact-${Date.now()}`),
    name: z.string().catch('이름 없음'),
    role: z.string().optional().catch(undefined),
    department: z.string().optional().catch(undefined),
    phone: z.string().optional().catch(undefined),
    email: z.string().optional().catch(undefined),
    isPrimary: z.boolean().catch(false),
});

export const CompanyMemoSchema = z.object({
    id: z.string().catch(() => `memo-${Date.now()}`),
    createdAt: z.string().catch(() => new Date().toISOString()),
    author: z.string().catch('시스템'),
    content: z.string().catch(''),
});

export const TimelineEventTypeSchema = z.enum(['status_change', 'call', 'email', 'note', 'meeting']).catch('note');

export const CompanyTimelineEventSchema = z.object({
    id: z.string().catch(() => `tl-${Date.now()}`),
    createdAt: z.string().catch(() => new Date().toISOString()),
    author: z.string().catch('시스템'),
    type: TimelineEventTypeSchema,
    content: z.string().catch(''),
    fromStatus: CaseStatusSchema.optional().catch(undefined),
    toStatus: CaseStatusSchema.optional().catch(undefined),
});

// Company Schema (Safe Parsing Core)
export const CompanySchema = z.object({
    id: z.string().catch(() => `comp-${Math.random()}`),
    name: z.string().catch('알 수 없는 기업'),
    biz: z.string().catch('미상'),
    url: z.string().catch(''),
    email: z.string().catch(''),
    phone: z.string().catch(''),
    storeCount: z.number().catch(0),
    status: CaseStatusSchema,
    assignedLawyer: z.string().catch(''),
    assignedSalesId: z.string().optional().catch(undefined),
    assignedSalesName: z.string().optional().catch(undefined),
    lawyerProfile: LawyerProfileSchema.optional().catch(undefined),
    assignedAt: z.string().optional().catch(undefined),
    salesQueueIndex: z.number().optional().catch(undefined),
    issues: z.array(IssueSchema).catch([]),
    salesConfirmed: z.boolean().catch(false),
    salesConfirmedAt: z.string().catch(''),
    salesConfirmedBy: z.string().catch(''),
    lawyerConfirmed: z.boolean().catch(false),
    lawyerConfirmedAt: z.string().catch(''),
    emailSentAt: z.string().catch(''),
    emailSubject: z.string().catch(''),
    clientReplied: z.boolean().catch(false),
    clientRepliedAt: z.string().catch(''),
    clientReplyNote: z.string().catch(''),
    loginCount: z.number().catch(0),
    callNote: z.string().catch(''),
    plan: z.enum(['none', 'starter', 'standard', 'premium']).catch('none'),
    createdAt: z.string().catch(() => new Date().toISOString()),
    updatedAt: z.string().catch(() => new Date().toISOString()),
    autoMode: z.boolean().catch(false),
    aiDraftReady: z.boolean().catch(false),
    source: z.enum(['manual', 'crawler']).catch('manual'),
    audit_report: z.string().optional().catch(undefined),
    auditReport: z.string().optional().catch(undefined),
    riskScore: z.number().catch(0),
    riskLevel: z.enum(['HIGH', 'MEDIUM', 'LOW', '']).catch(''),
    issueCount: z.number().catch(0),
    bizType: z.string().catch(''),
    franchiseType: z.string().optional().catch(undefined),
    domain: z.string().catch(''),
    privacyUrl: z.string().catch(''),
    privacyPolicyText: z.string().optional().catch(undefined),
    ceo: z.string().optional().catch(undefined),
    contactName: z.string().catch(''),
    contactEmail: z.string().catch(''),
    contactPhone: z.string().catch(''),
    contacts: z.array(CompanyContactSchema).catch([]),
    memos: z.array(CompanyMemoSchema).catch([]),
    timeline: z.array(CompanyTimelineEventSchema).catch([]),
    customScript: z.any().optional().catch(undefined),
    lawyerNote: z.string().optional().catch(undefined),
    contractSentAt: z.string().optional().catch(undefined),
    contractSignedAt: z.string().optional().catch(undefined),
    contractMethod: z.enum(['email', 'system', 'offline']).optional().catch(undefined),
    contractNote: z.string().optional().catch(undefined),
    callbackScheduledAt: z.string().optional().catch(undefined),
    followUpStep: z.number().optional().catch(undefined),
    aiMemoSummary: z.string().optional().catch(undefined),
    aiNextAction: z.string().optional().catch(undefined),
    aiNextActionType: z.string().optional().catch(undefined),
    lastCallResult: z.enum(['connected', 'no_answer', 'callback', 'rejected', 'invalid_site', 'no_homepage', 'promo_only', 'no_policy']).optional().catch(undefined),
    lastCallAt: z.string().optional().catch(undefined),
    lastCalledBy: z.string().optional().catch(undefined),
    callAttempts: z.number().optional().catch(undefined),
    industry_type: z.string().optional().catch('해당없음'),
    headcount: z.number().optional().catch(0),
    annual_revenue: z.number().optional().catch(0),
    lastContactedAt: z.string().optional().catch(undefined),
    nextFollowupAt: z.string().optional().catch(undefined),
    hubspotId: z.string().optional().catch(undefined),
    campaignId: z.string().optional().catch(undefined),
    leadSource: z.string().optional().catch(undefined),
    scoreReasons: z.array(z.string()).optional().catch([]),
}).catch((ctx) => {
    // If the entire object is invalid or not an object, return a safely stubbed object
    return {
        id: `comp-err-${Math.random()}`,
        name: '데이터 파싱 오류 (안전 모드)',
        biz: '',
        url: '',
        email: '',
        phone: '',
        storeCount: 0,
        status: 'pending' as const,
        assignedLawyer: '',
        issues: [],
        salesConfirmed: false,
        salesConfirmedAt: '',
        salesConfirmedBy: '',
        lawyerConfirmed: false,
        lawyerConfirmedAt: '',
        emailSentAt: '',
        emailSubject: '',
        clientReplied: false,
        clientRepliedAt: '',
        clientReplyNote: '',
        loginCount: 0,
        callNote: '데이터 파싱 에러 방지를 위해 기본값이 할당되었습니다.',
        plan: 'none' as const,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        autoMode: false,
        aiDraftReady: false,
        source: 'manual' as const,
        riskScore: 0,
        riskLevel: '' as const,
        issueCount: 0,
        bizType: '',
        domain: '',
        privacyUrl: '',
        contactName: '',
        contactEmail: '',
        contactPhone: '',
        contacts: [],
        memos: [],
        timeline: [],
    };
});

// A wrapper schema for pagination response
export const PaginatedCompaniesSchema = z.object({
  data: z.array(CompanySchema).catch([]),
  count: z.number().catch(0),
}).catch({ data: [], count: 0 });
