import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Bot } from 'lucide-react';
import { AutoSettings, AutoLog } from '@/lib/types';
import { T } from './shared';

interface AutoSettingsPanelProps {
    autoSettings: AutoSettings;
    autoLogs: AutoLog[];
    updateAuto: (patch: Partial<AutoSettings>) => void;
    clearLogs: () => void;
}

export default function AutoSettingsPanel({ autoSettings, autoLogs, updateAuto, clearLogs }: AutoSettingsPanelProps) {
    const [autoTab, setAutoTab] = useState<'settings' | 'logs'>('settings');

    return (
        <motion.div key="auto-panel" initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} className="mb-5">
            <div className="rounded-2xl overflow-hidden" style={{ border: `1px solid #86efac`, background: T.card, boxShadow: '0 2px 12px rgba(0,0,0,0.08)' }}>
                <div className="flex items-center" style={{ background: '#f0fdf4', borderBottom: '1px solid #bbf7d0' }}>
                    {(['settings', 'logs'] as const).map(t => (
                        <button key={t} onClick={() => setAutoTab(t)}
                            className="px-5 py-3 text-xs font-black transition-all whitespace-nowrap"
                            style={{ color: autoTab === t ? '#16a34a' : T.muted, borderBottom: `2px solid ${autoTab === t ? '#16a34a' : 'transparent'}` }}>
                            {t === 'settings' ? '⚙️ 자동화 설정' : `📜 실행 기록 (${autoLogs.length})`}
                        </button>
                    ))}
                    {autoSettings.updatedAt && (
                        <span className="ml-auto pr-4 text-[10px]" style={{ color: T.faint }}>
                            마지막 변경: <strong style={{ color: T.sub }}>{autoSettings.updatedBy}</strong> {autoSettings.updatedAt}
                        </span>
                    )}
                </div>
                <AnimatePresence mode="wait">
                    {autoTab === 'settings' && (
                        <motion.div key="settings" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="p-5">
                            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-4">
                                {([
                                    { k: 'autoGenerateDraft', l: '초안 자동 생성', sub: '법률 기준 수정문구', color: '#2563eb', on: '✅ 변호사 검토 전 초안 자동 생성', off: '❌ 변호사가 직접 초안 작성' },
                                    { k: 'autoSendEmail', l: '이메일 자동 발송', sub: '컨펌 즉시 발송', color: '#16a34a', on: '✅ 컨펌 즉시 자동 발송', off: '❌ 영업팀이 발송 버튼 클릭' },
                                ] as { k: keyof AutoSettings; l: string; sub: string; color: string; on: string; off: string }[]).map(item => (
                                    <button key={item.k}
                                        onClick={() => updateAuto({ [item.k]: !autoSettings[item.k] })}
                                        className="p-4 rounded-xl text-left transition-all"
                                        style={{ background: autoSettings[item.k] ? `${item.color}10` : '#f8f9fc', border: `1px solid ${autoSettings[item.k] ? item.color + '40' : T.borderSub}` }}>
                                        <div className="flex items-center justify-between mb-2">
                                            <p className="text-xs font-black" style={{ color: autoSettings[item.k] ? item.color : T.sub }}>{item.l}</p>
                                            <div className="w-9 h-5 rounded-full relative flex-shrink-0" style={{ background: autoSettings[item.k] ? item.color : '#cbd5e1' }}>
                                                <div className="absolute top-1 w-3 h-3 rounded-full bg-white shadow-sm transition-all" style={{ left: autoSettings[item.k] ? '21px' : '3px' }} />
                                            </div>
                                        </div>
                                        <p className="text-[10px] mb-1.5 font-medium" style={{ color: T.muted }}>{item.sub}</p>
                                        <p className="text-[10px] leading-relaxed" style={{ color: autoSettings[item.k] ? item.color : T.faint }}>
                                            {autoSettings[item.k] ? item.on : item.off}
                                        </p>
                                    </button>
                                ))}
                            </div>
                            <div className="rounded-xl p-3" style={{ background: '#f0fdf4', border: '1px solid #86efac' }}>
                                <p className="text-[11px] font-medium" style={{ color: T.sub }}>
                                    💡 <strong style={{ color: '#16a34a' }}>모두 ON</strong>: 기업등록 → 자동분석 → 자동컨펌 → 자동배정 → <strong style={{ color: '#d97706' }}>변호사 검토·컨펌(유일한 수동)</strong> → 자동이메일발송.
                                </p>
                            </div>
                        </motion.div>
                    )}
                    {autoTab === 'logs' && (
                        <motion.div key="logs" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="p-4">
                            <div className="flex items-center justify-between mb-3">
                                <p className="text-xs font-bold" style={{ color: T.sub }}>자동화 실행 기록 {autoLogs.length}건</p>
                                <button onClick={clearLogs}
                                    className="text-[10px] px-2 py-1 rounded-lg font-semibold"
                                    style={{ color: T.muted, background: '#f1f5f9', border: `1px solid ${T.borderSub}` }}>기록 삭제</button>
                            </div>
                            {autoLogs.length === 0 ? (
                                <div className="text-center py-10" style={{ color: T.faint }}>
                                    <Bot className="w-8 h-8 mx-auto mb-2 opacity-30" />
                                    <p className="text-sm font-medium">아직 자동화 기록이 없습니다</p>
                                </div>
                            ) : (
                                <div className="space-y-1.5 max-h-72 overflow-y-auto pr-1">
                                    {autoLogs.map(log => {
                                        const colors: Record<string, string> = { ai_analysis: '#2563eb', auto_confirm: '#7c3aed', auto_assign: '#d97706', auto_email: '#16a34a', setting_change: '#d97706' };
                                        const icons: Record<string, string> = { ai_analysis: '🤖', auto_confirm: '✅', auto_assign: '⚖️', auto_email: '📧', setting_change: '⚙️' };
                                        const cl = colors[log.type] ?? T.muted;
                                        return (
                                            <div key={log.id} className="flex items-start gap-3 px-3 py-2.5 rounded-xl"
                                                style={{ background: '#f8f9fc', border: `1px solid ${T.borderSub}` }}>
                                                <span className="text-base flex-shrink-0 leading-none mt-0.5">{icons[log.type]}</span>
                                                <div className="flex-1 min-w-0">
                                                    <div className="flex items-center gap-2 flex-wrap">
                                                        <p className="text-[11px] font-black" style={{ color: cl }}>{log.label}</p>
                                                        {log.companyName && <span className="text-[10px] px-1.5 py-0.5 rounded-full font-medium" style={{ background: '#e5e7eb', color: T.sub }}>{log.companyName}</span>}
                                                    </div>
                                                    <p className="text-[10px] mt-0.5 font-medium" style={{ color: T.muted }}>{log.detail}</p>
                                                    {log.prevValue && log.newValue && (
                                                        <p className="text-[10px] mt-0.5" style={{ color: T.faint }}>{log.prevValue} → {log.newValue}</p>
                                                    )}
                                                </div>
                                                <p className="text-[10px] flex-shrink-0 font-mono mt-0.5" style={{ color: T.faint }}>{log.at}</p>
                                            </div>
                                        );
                                    })}
                                </div>
                            )}
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>
        </motion.div>
    );
}
