// src/lib/mock/consultStore.ts — 법률 상담 시스템
// mockStore.ts에서 분리. ConsultStore 클래스 + genAiAnswer 포함.

import type { Consultation, ConsultCategory, ConsultUrgency, AutoSettings } from './types';
import { LAWYERS } from './constants';

const CONSULT_KEY = 'ibs_consult_v1';
const AUTO_KEY = 'ibs_auto_settings';

// ── AI 답변 mock ──────────────────────────────────────────────
function genAiAnswer(category: ConsultCategory, _body: string): { answer: string; law: string[]; confidence: number } {
    const map: Record<ConsultCategory, { answer: string; law: string[] }> = {
        '가맹계약': {
            answer: `가맹사업거래의 공정화에 관한 법률(가맹사업법)에 따르면, 가맹본부는 가맹계약서를 계약 체결 14일 전에 제공해야 합니다.\n\n귀하의 질의 내용을 검토한 결과, 계약서 내 위약금 조항이 가맹사업법 시행령 제14조 기준을 초과할 가능성이 있습니다. 변호사 검토 후 구체적인 조치를 권장합니다.\n\n[AI 1차 분석 — 변호사 교차검증 후 최종 확인]`,
            law: ['가맹사업거래의 공정화에 관한 법률 제7조', '동법 시행령 제14조'],
        },
        '개인정보': {
            answer: `개인정보보호법 제29조에 따라 개인정보처리자는 안전성 확보에 필요한 기술적·관리적·물리적 조치를 취해야 합니다.\n\n귀하의 상황에서는 동의서 재수집 절차와 처리방침 개정이 우선적으로 필요해 보입니다. 위반 시 과태료가 최대 3,000만원에 달할 수 있습니다.\n\n[AI 1차 분석 — 변호사 교차검증 후 최종 확인]`,
            law: ['개인정보보호법 제29조', '동법 제30조 제1항'],
        },
        '형사': {
            answer: `형사 사안은 즉각적인 법률 전문가 상담이 필요합니다. 현재 AI 분석만으로는 형사 리스크 수준을 정확히 판단하기 어려우며, 담당 변호사의 긴급 개입이 권장됩니다.\n\n콜백을 요청하시면 익일 영업일 내 담당 변호사가 직접 연락드립니다.\n\n[AI 1차 분석 — 담당 변호사 긴급 배정 권장]`,
            law: ['형법 제347조(사기)', '형사소송법 제244조'],
        },
        '노무': {
            answer: `근로기준법 및 최저임금법에 따른 검토 결과, 근로계약서 미작성·최저임금 미달·초과근무 미지급 등이 주요 위험 요인입니다.\n\n가맹점의 경우도 가맹점주 사용자 책임이 인정될 수 있어 본사 차원의 가이드라인 정비가 필요합니다.\n\n[AI 1차 분석 — 변호사 교차검증 후 최종 확인]`,
            law: ['근로기준법 제17조', '최저임금법 제6조'],
        },
        '지식재산': {
            answer: `상표권·저작권 관련 분쟁은 상표법 및 저작권법에 따라 판단됩니다. 유사 상표 사용은 상표법 제108조 위반으로 형사처벌 대상이 될 수 있습니다.\n\n가맹계약 내 IP 사용 조항을 재검토하고, 상표 사용 허락 범위를 명확히 하는 것이 권장됩니다.\n\n[AI 1차 분석 — 변호사 교차검증 후 최종 확인]`,
            law: ['상표법 제108조', '저작권법 제136조'],
        },
        '기타': {
            answer: `귀하의 질의를 검토한 결과, 관련 법령 및 판례 분석이 필요합니다. 담당 변호사가 구체적인 사실관계를 확인 후 정확한 법적 견해를 제공해 드릴 예정입니다.\n\n48시간 내 답변을 드리겠으며, 긴급한 경우 콜백을 요청하시면 익일 영업일 내 연락드립니다.\n\n[AI 1차 분석 — 변호사 교차검증 후 최종 확인]`,
            law: ['민법 제750조(불법행위)', '상법 제1조'],
        },
    };
    const conf = category === '형사' ? 52 : category === '기타' ? 65 : Math.floor(Math.random() * 20) + 75;
    return { answer: map[category].answer, law: map[category].law, confidence: conf };
}

// 라운드로빈 변호사 배정
function loadAutoSettings(): AutoSettings {
    if (typeof window === 'undefined') return { autoSalesConfirm: true, autoAssignLawyer: true, autoGenerateDraft: true, autoSendEmail: true, lawyerRoundRobin: 0, updatedAt: '', updatedBy: '시스템' };
    try { return JSON.parse(localStorage.getItem(AUTO_KEY) || '{}'); } catch { return {} as AutoSettings; }
}
function saveAutoSettings(s: AutoSettings) {
    if (typeof window !== 'undefined') localStorage.setItem(AUTO_KEY, JSON.stringify(s));
}

function assignNextLawyer(): string {
    const s = loadAutoSettings();
    const lawyer = LAWYERS[s.lawyerRoundRobin % LAWYERS.length];
    saveAutoSettings({ ...s, lawyerRoundRobin: (s.lawyerRoundRobin + 1) % LAWYERS.length });
    return lawyer;
}

// ── 기본 상담 데이터 ──────────────────────────────────────────
const DEFAULT_CONSULTATIONS: Consultation[] = [
    {
        id: 'q1', companyId: 'c1', companyName: '(주)놀부NBG', branchName: '강남1호점', authorName: '김가맹', authorRole: '가맹점주',
        category: '가맹계약', urgency: 'normal', title: '계약 갱신 거절 통보 받았습니다',
        body: '본사에서 5년 계약 만료 후 갱신 거절 공문을 받았습니다. 이게 법적으로 가능한가요? 보증금 환급도 요청했는데 묵묵부답입니다.',
        aiAnswer: genAiAnswer('가맹계약', '').answer, aiConfidence: 82, aiLaw: ['가맹사업거래의 공정화에 관한 법률 제7조', '동법 시행령 제14조'],
        lawyerAnswer: '', assignedLawyer: '이지원 변호사', assignedAt: '2026-02-28 09:00',
        answeredAt: '', callbackPhone: '', callbackRequestedAt: '', callbackDoneAt: '', callbackNote: '',
        status: 'assigned', createdAt: '2026-02-28 08:30', updatedAt: '2026-02-28 09:00', isPrivate: true,
    },
    {
        id: 'q2', companyId: 'c3', companyName: '(주)파리바게뜨', branchName: '분당판교점', authorName: '박점주', authorRole: '가맹점주',
        category: '개인정보', urgency: 'urgent', title: '개인정보보호위원회 조사 통보 받았습니다 — 긴급',
        body: '오늘 개인정보보호위원회로부터 현장조사 통보를 받았습니다. 다음주 월요일 방문 예정입니다. 어떻게 대응해야 하나요? 처리방침이 오래됐습니다.',
        aiAnswer: genAiAnswer('개인정보', '').answer, aiConfidence: 78, aiLaw: ['개인정보보호법 제29조', '동법 제30조 제1항'],
        lawyerAnswer: '', assignedLawyer: '', assignedAt: '',
        answeredAt: '', callbackPhone: '010-1234-5678', callbackRequestedAt: '2026-02-28 10:15',
        callbackDoneAt: '', callbackNote: '',
        status: 'callback_requested', createdAt: '2026-02-28 10:00', updatedAt: '2026-02-28 10:15', isPrivate: true,
    },
    {
        id: 'q3', companyId: 'c4', companyName: '(주)bhc치킨', branchName: '본사 인사팀', authorName: '이담당', authorRole: '임직원',
        category: '노무', urgency: 'normal', title: '가맹점 아르바이트 최저임금 위반 민원',
        body: '가맹점에서 알바 직원이 최저임금 위반 민원을 고용노동부에 제기했다는 연락이 왔습니다. 본사가 공동 책임을 질 수 있나요?',
        aiAnswer: genAiAnswer('노무', '').answer, aiConfidence: 79, aiLaw: ['근로기준법 제17조', '최저임금법 제6조'],
        lawyerAnswer: `귀하의 질의를 검토한 결과, 가맹본부의 사용자 책임 인정 여부는 가맹점에 대한 지배·관리 정도에 따라 판단됩니다.\n\n최근 판례(서울고법 2024나12345)에 따르면 본사가 인사·노무에 실질적 개입을 한 경우 공동사용자로 인정될 수 있습니다.\n\n**권장 조치:**\n1. 해당 가맹점 근로계약서 즉시 확인\n2. 가맹계약서 내 노무 관련 조항 점검\n3. 고용노동부 조사 전 자체감사 실시\n\n추가 상담이 필요하시면 연락주십시오.\n\n— 김수현 변호사`,
        assignedLawyer: '김수현 변호사', assignedAt: '2026-02-27 11:00',
        answeredAt: '2026-02-27 16:30', callbackPhone: '', callbackRequestedAt: '', callbackDoneAt: '', callbackNote: '',
        status: 'answered', createdAt: '2026-02-27 10:00', updatedAt: '2026-02-27 16:30', isPrivate: false,
    },
];

// ── ConsultStore 클래스 ────────────────────────────────────────
class ConsultStore {
    private items: Consultation[] = [];

    constructor() {
        if (typeof window === 'undefined') { this.items = [...DEFAULT_CONSULTATIONS]; return; }
        const saved = localStorage.getItem(CONSULT_KEY);
        this.items = saved ? JSON.parse(saved) : [...DEFAULT_CONSULTATIONS];
    }

    private save() { if (typeof window !== 'undefined') localStorage.setItem(CONSULT_KEY, JSON.stringify(this.items)); }

    getAll(): Consultation[] { return [...this.items].sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
    getByCompany(cid: string): Consultation[] { return this.getAll().filter(q => q.companyId === cid); }
    getById(id: string): Consultation | undefined { return this.items.find(q => q.id === id); }
    getUnassigned(): Consultation[] { return this.getAll().filter(q => q.status === 'ai_done' || q.status === 'callback_requested'); }
    getForLawyer(lawyer: string): Consultation[] { return this.getAll().filter(q => q.assignedLawyer === lawyer || q.status === 'ai_done'); }

    submit(data: {
        companyId: string; companyName: string; branchName: string;
        authorName: string; authorRole: Consultation['authorRole'];
        category: ConsultCategory; title: string; body: string;
        urgency: ConsultUrgency; callbackPhone?: string; isPrivate?: boolean;
    }): Consultation {
        const now = new Date().toLocaleString('ko-KR');
        const ai = genAiAnswer(data.category, data.body);
        const q: Consultation = {
            id: `q${Date.now()}`,
            ...data,
            aiAnswer: ai.answer, aiConfidence: ai.confidence, aiLaw: ai.law,
            lawyerAnswer: '', assignedLawyer: '', assignedAt: '',
            answeredAt: '', callbackPhone: data.callbackPhone || '',
            callbackRequestedAt: data.urgency === 'urgent' && data.callbackPhone ? now : '',
            callbackDoneAt: '', callbackNote: '',
            status: 'ai_analyzing',
            createdAt: now, updatedAt: now, isPrivate: data.isPrivate ?? true,
        };
        this.items.unshift(q);
        this.save();
        setTimeout(() => {
            const idx = this.items.findIndex(x => x.id === q.id);
            if (idx >= 0) {
                this.items[idx].status = data.urgency === 'urgent' ? 'callback_requested' : 'ai_done';
                this.items[idx].updatedAt = new Date().toLocaleString('ko-KR');
                this.save();
            }
        }, 1500);
        return q;
    }

    assignLawyer(id: string, lawyer?: string): void {
        const q = this.items.find(x => x.id === id);
        if (!q) return;
        q.assignedLawyer = lawyer || assignNextLawyer();
        q.assignedAt = new Date().toLocaleString('ko-KR');
        q.status = 'assigned';
        q.updatedAt = q.assignedAt;
        this.save();
    }

    saveLawyerDraft(id: string, draft: string): void {
        const q = this.items.find(x => x.id === id);
        if (!q) return;
        q.lawyerAnswer = draft;
        q.status = 'reviewing';
        q.updatedAt = new Date().toLocaleString('ko-KR');
        this.save();
    }

    sendAnswer(id: string, answer: string): void {
        const q = this.items.find(x => x.id === id);
        if (!q) return;
        q.lawyerAnswer = answer;
        q.answeredAt = new Date().toLocaleString('ko-KR');
        q.status = 'answered';
        q.updatedAt = q.answeredAt;
        this.save();
    }

    markCallbackDone(id: string, note: string): void {
        const q = this.items.find(x => x.id === id);
        if (!q) return;
        q.callbackDoneAt = new Date().toLocaleString('ko-KR');
        q.callbackNote = note;
        q.status = 'callback_done';
        q.updatedAt = q.callbackDoneAt;
        this.save();
    }

    requestCallback(id: string, phone: string): void {
        const q = this.items.find(x => x.id === id);
        if (!q) return;
        q.callbackPhone = phone;
        q.callbackRequestedAt = new Date().toLocaleString('ko-KR');
        q.status = 'callback_requested';
        q.updatedAt = q.callbackRequestedAt;
        this.save();
    }
}

export const consultStore = new ConsultStore();
