// src/lib/mock/types.ts — 모든 타입 정의
// mockStore.ts에서 분리. 원본 923줄 → types만 추출.

// ── 역할(Role) 시스템 ─────────────────────────────────────────
export type RoleType =
    | 'super_admin'
    | 'admin'
    | 'sales'
    | 'lawyer'
    | 'litigation'
    | 'general'
    | 'hr'
    | 'finance'
    | 'counselor'
    | 'client_hr';

// ── 모듈 레지스트리 ──────────────────────────────────────────
export type ModuleStatus = 'active' | 'beta' | 'coming_soon';

export interface ModuleDefinition {
    id: string;
    href: string;
    label: string;
    icon: string;
    roles: RoleType[];
    status: ModuleStatus;
    hideable: boolean;
    badge?: 'employee' | 'lawyer' | 'admin' | 'litigation';
    phase: 1 | 2 | 3;
}

// ── 회사 관련 ────────────────────────────────────────────────
export type CaseStatus =
    | 'pending'
    | 'crawling'
    | 'analyzed'
    | 'sales_confirmed'
    | 'assigned'
    | 'reviewing'
    | 'lawyer_confirmed'
    | 'emailed'
    | 'client_replied'
    | 'subscribed';

export interface Issue {
    id: string;
    level: 'HIGH' | 'MEDIUM' | 'LOW';
    law: string;
    title: string;
    originalText: string;
    riskDesc: string;
    customDraft: string;
    lawyerNote: string;
    reviewChecked: boolean;
    aiDraftGenerated: boolean;
}

export interface Company {
    id: string;
    name: string;
    biz: string;
    url: string;
    email: string;
    phone: string;
    storeCount: number;
    status: CaseStatus;
    assignedLawyer: string;
    issues: Issue[];
    salesConfirmed: boolean;
    salesConfirmedAt: string;
    salesConfirmedBy: string;
    lawyerConfirmed: boolean;
    lawyerConfirmedAt: string;
    emailSentAt: string;
    emailSubject: string;
    clientReplied: boolean;
    clientRepliedAt: string;
    clientReplyNote: string;
    loginCount: number;
    callNote: string;
    plan: 'none' | 'starter' | 'standard' | 'premium';
    createdAt: string;
    updatedAt: string;
    autoMode: boolean;
    aiDraftReady: boolean;
    source: 'manual' | 'crawler';
    paymentVerified: boolean;
    paymentVerifiedAt: string;
}

// ── 송무팀 ──────────────────────────────────────────────────
export type LitigationStatus =
    | 'preparing'
    | 'filed'
    | 'hearing'
    | 'settlement'
    | 'judgment'
    | 'closed';

export interface LitigationDeadline {
    id: string;
    label: string;
    dueDate: string;
    completed: boolean;
    completedAt: string;
}

export interface LitigationCase {
    id: string;
    companyId: string;
    companyName: string;
    caseNo: string;
    court: string;
    type: string;
    opponent: string;
    claimAmount: number;
    status: LitigationStatus;
    assignedLawyer: string;
    deadlines: LitigationDeadline[];
    notes: string;
    result: '' | '승소' | '패소' | '합의' | '취하';
    resultNote: string;
    createdAt: string;
    updatedAt: string;
}

// ── 자동화 설정 ──────────────────────────────────────────────
export interface AutoSettings {
    autoSalesConfirm: boolean;
    autoAssignLawyer: boolean;
    autoGenerateDraft: boolean;
    autoSendEmail: boolean;
    lawyerRoundRobin: number;
    updatedAt: string;
    updatedBy: string;
}

export interface AutoLog {
    id: string;
    at: string;
    type: 'auto_confirm' | 'auto_assign' | 'auto_email' | 'setting_change' | 'ai_analysis';
    label: string;
    companyName?: string;
    detail: string;
    prevValue?: string;
    newValue?: string;
}

// ── 법률 상담 ──────────────────────────────────────────────
export type ConsultCategory = '가맹계약' | '개인정보' | '형사' | '노무' | '지식재산' | '기타';
export type ConsultUrgency = 'urgent' | 'normal';
export type ConsultStatus =
    | 'submitted'
    | 'ai_analyzing'
    | 'ai_done'
    | 'assigned'
    | 'reviewing'
    | 'answered'
    | 'callback_requested'
    | 'callback_done';

export interface Consultation {
    id: string;
    companyId: string;
    companyName: string;
    branchName: string;
    authorName: string;
    authorRole: '가맹점주' | '임직원' | '본사직원';
    category: ConsultCategory;
    urgency: ConsultUrgency;
    title: string;
    body: string;
    aiAnswer: string;
    aiConfidence: number;
    aiLaw: string[];
    lawyerAnswer: string;
    assignedLawyer: string;
    assignedAt: string;
    answeredAt: string;
    callbackPhone: string;
    callbackRequestedAt: string;
    callbackDoneAt: string;
    callbackNote: string;
    status: ConsultStatus;
    createdAt: string;
    updatedAt: string;
    isPrivate: boolean;
}
